apiVersion : apps/v1
kind: Deployment
metadata:
  name: "serapismedicalapi-22d4"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "serapismedicalapi-22d44"
  template:
    metadata:
      labels:
        app: "serapismedicalapi-22d4"
    spec:
      containers:
        - name: "serapismedicalapi-22d4"
          image: "serapismedicalapi.azurecr.io/kbaalphaclusterqa"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 80
