apiVersion : apps/v1
kind: Deployment
metadata:
  name: "kbalphaqa-99b4"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "kbalphaqa-99b4"
  template:
    metadata:
      labels:
        app: "kbalphaqa-99b4"
    spec:
      containers:
        - name: "kbalphaqa-99b4"
          image: "serapismedicalapi.azurecr.io/kbalphaqa"
          ports:
          - containerPort: 80