apiVersion : apps/v1
kind: Deployment
metadata:
  name: "kbaalphaclusterqa-22d4"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "kbaalphaclusterqa-22d4"
  template:
    metadata:
      labels:
        app: "kbaalphaclusterqa-22d4"
    spec:
      containers:
        - name: "kbaalphaclusterqa-22d4"
          image: "serapismedicalapi.azurecr.io/kbaalphaclusterqa"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 80
