apiVersion: v1
kind: Service
metadata:
    name: "kbaalphaclusterqa-22d4"
    labels:
        app: "kbaalphaclusterqa-22d4"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "kbaalphaclusterqa-22d4"
