jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: unit tests for Serapis API
        uses: zyborg/dotnet-tests-report@v1
        with:
          project_path: SerapisMedicalAPI.Tests
          report_name: SerapisMedicalAPI_Tests
          report_title: SerapisMedicalAPI Testss
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gist_name: serapismedical_tests.md
          gist_badge_label: 'Serapis Medical Business: %Counters_passed%/%Counters_total%'
          gist_token: ${{ secrets.GIST_TOKEN }}

      - name: unit tests for Serapis API2
        uses: zyborg/dotnet-tests-report@v1
        with:
          project_path: SerapisMedicalAPI.Tests
          report_name: SerapisMedicalAPI_Tests
          report_title: SerapisMedicalAPI Tests
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gist_name: contoso_service_tests.md
          gist_badge_label: 'Contoso Service: %Counters_passed%/%Counters_total%'
          gist_token: ${{ secrets.GIST_TOKEN }}
