on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: serapismedicalapi.azurecr.io
        username: ${{ secrets.acr_serapismedicalapi_username }}
        password: ${{ secrets.acr_serapismedicalapi_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t serapismedicalapi.azurecr.io/kbaalphaclusterqa:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push serapismedicalapi.azurecr.io/kbaalphaclusterqa:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kbaalphaclusterqa_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kbaalphaclusterqab016 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kbaalphaclusterqab016`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kbaalphaclusterqab016
        container-registry-url: serapismedicalapi.azurecr.io
        container-registry-username: ${{ secrets.acr_serapismedicalapi_username }}
        container-registry-password: ${{ secrets.acr_serapismedicalapi_password }}
        secret-name: kbaalphaclusdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: kbaalphaclusterqab016
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          serapismedicalapi.azurecr.io/kbaalphaclusterqa:${{ github.sha }}
        imagepullsecrets: |
          kbaalphaclusdockerauth
