# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - serapismedicalapi

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://serapismedicalapi.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_df1f594e44f449fdadf8581c8d254ef3 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d04425f7c3554d13bc63d98339f4f946 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: serapismedicalapi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_df1f594e44f449fdadf8581c8d254ef3 }}/serapismedicalapi/serapismedicalapi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'serapismedicalapi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1f3d78e0fc7c4fccb094e8987d4c6eb1 }}
        images: 'serapismedicalapi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_df1f594e44f449fdadf8581c8d254ef3 }}/serapismedicalapi/serapismedicalapi:${{ github.sha }}'